### PR TITLE
Use `ProjectTo` in broadcasting & `gradient`

### LINKED ISSUE #342: Complex gradient on real function with complex intermediates
I came across something odd while working with complex numbers:

```julia
julia> using Zygote
julia> Zygote.gradient(x->real(x + 2.0*im), 3.0)
(1.0,)
julia> Zygote.gradient(x->imag(x + 2.0*im), 3.0)
(0.0 + 1.0im,)
```

While the inputs and outputs of both functions are real, the first produces a real gradient, while the second produces a complex gradient. Is this Zygote's intended behavior?

Version info:

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

(v1.2) pkg> st --manifest Zygote
    Status `~/.julia/environments/v1.2/Manifest.toml`
  [b552c78f] DiffRules v0.0.10
  [7a1cc6ca] FFTW v0.3.0
  [1a297f60] FillArrays v0.6.4
  [f6369f11] ForwardDiff v0.10.3
  [7869d1d1] IRTools v0.2.3
  [1914dd2f] MacroTools v0.5.1
  [872c559c] NNlib v0.6.0
  [77ba4419] NaNMath v0.3.2
  [ae029012] Requires v0.5.2
  [276daf66] SpecialFunctions v0.7.2
  [e88e6eb3] Zygote v0.3.4
  [700de1a5] ZygoteRules v0.1.0
  [b77e0a4c] InteractiveUtils 
  [37e2e46d] LinearAlgebra 
  [9a3f8284] Random 
  [10745b16] Statistics 
```

### LINKED ISSUE #402: Adjoints for functions of specialized matrices
I encountered an error with the adjoint of `getindex` of a [special
matrix](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Special-matrices-1). The issue is that the current `getindex` adjoints tries to assign to an element in the special matrix, which is not always allowed. It points to a more general problem/opportunity for adjoints of function of special matrices. Using `Diagonal` as an example, this is the error:
```julia
using LinearAlgebra
using Zygote
using Random
rng = MersenneTwister(54754)
n = 3
A = rand(rng,n,n)

y,B_getindex = Zygote.pullback(x->getindex(x,2,1),Diagonal(A))
bA = B_getindex(1)[1] |> display
#ArgumentError: cannot set off-diagonal entry (2, 1) to a nonzero value (1)
```
Two potential possible are:

**Solution A** : adjoint is a tuple with an unconstrained array
```julia
# Copy of getindex(D::Diagonal,...)
using LinearAlgebra:diagzero
@inline function getindex_duplicate(D::Diagonal, i::Int, j::Int)
  @boundscheck checkbounds(D, i, j)
  if i == j
      @inbounds r = D.diag[i]
  else
      r = diagzero(D, i, j)
  end
  r
end

yA,∂getindexA = Zygote.pullback(x->getindex_duplicate(x,3,3),Diagonal(A))
D̄A = ∂getindexA(1)[1]
display(D̄A)
# (diag = [0.0, 0.0, 1.0],)
```
Pro: Simple.
Con: The adjoint does not return a `Diagonal`. This reduces the efficiency of the adjoint code. This can perhaps be a fallback, as we implement solution B.

**Solution B** : Insert orthogonal projection and return a special matrix
```julia
getindexB(D::Diagonal,i::Int,j::Int) = getindex(A,i,j)
Zygote.@adjoint getindexB(D::Diagonal,i::Int,j::Int) = begin
  y,∂U = Zygote.pullback(x->getindex_duplicate(x,i,j),D)
  y, function(Ȳ)
    D̄U = ∂U(Ȳ)[1]
    D̄ = Diagonal(D̄U.diag)
    return D̄, nothing, nothing
  end
end

yB,∂getindexB = Zygote.pullback(x->getindexB(x,3,3),Diagonal(A))
D̄B = ∂getindexB(1)[1]
display(D̄B)
#3×3 Diagonal{Float64,Array{Float64,1}}:
# 0.0   ⋅    ⋅
#  ⋅   0.0   ⋅
#  ⋅    ⋅   1.0
```
Pro: Returns a special matrix, so the adjoint code becomes more efficient.
Con: Some work to write the adjoint.

Both solutions provide the same gradients:
```julia
ftestA(x) = getindex_duplicate(Diagonal(x.^2),3,3)
ftestB(x) = getindexB(Diagonal(x.^2),3,3)
x = [0.3,-2.5,4.3]
gA = Zygote.gradient(ftestA,x)[1]
gB = Zygote.gradient(ftestB,x)[1]
display(gA==gB)
# true
```
**Mathematical background solution B**
Suppose we have a special matrix S ∈ 𝕊. For example, for `Diagonal`, 𝕊 is  the space of diagonal matrices. 𝕊 is a subspace of the space of the regular matrices ℤ: 𝕊 ⊂ ℤ. The original function maps from 𝕊 to 𝕐:
Y = f(S) : 𝕊 → 𝕐
For example, for `getindex(S,i::Int,j::Int)`, 𝕐 is scalar, so 𝕐 = ℝ.  If we take the adjoint through the the code of `f`, we currently get a unconstrained matrix S̄ ∈ ℝ, as shown above for `getindex`. To ensure that S̄ ∈ 𝕊, we insert a orthogonal projection P from ℤ to 𝕊:
S = P(Z) : ℤ → 𝕊
Note that:
1) For S ∈ 𝕊, P is the identity: P(S) = S
2) Because P is an orthogonal projection, it is self-adjoint: P' = P. Therefore, the adjoint also maps ℤ → 𝕊. 

Instead of computing the adjoint for f, we compute it for a function g
g = f∘P
which is:
g' = P∘f'
Because of property 1, g=f for all special matrix S ∈ 𝕊. 

This methodology applies to, among others: `Diagonal`, `Symmetric`, `UpperDiagonal`, `LowerDiagonal`, `I`(UniformScaling)(?). Often, P is simply the constructor (`Diagonal`, `UpperDiagonal`, `LowerDiagonal`). For Symmetric, it is `P(A) = (A+transpose(A))/2`

**Beyond `getindex`**
In general, this approach could be used for adjoints of functions mapping from the constrained to the unconstrained space, where the adjoint is not guaranteed to map to 𝕊, notably `collect` and `Array()`. As with `getindex`, specializing the current adjoint to `Array` will probably give you solution A for these. It should be noted that the adjoint for these functions do work now, unlike `getindex`, so coding these adjoints is less urgent.

**Open questions**
1) Is solution A or solution B preferred? I think B, using A as a fallback
2) Do we need to restrict the current adjoint for `getindex` to apply only to `Array` instead of `AbstractArray`? (I think is was like this in the past). This would have the benefit that solution A is automatically used for special matrices. But I don't know what are the repercussions of this. With the current signature of the `getindex` adjoint, I don't see how I can circumvent it to autodiff through the original `getindex` code in solution B, apart from creating a duplicate, which is of course a undesirable.

If there is an interest in this, I am happy to start a branch to start implementing some of this. I would appreciate guidance and help from others to get it right!

### LINKED ISSUE #431: Gradient of inv and logdet UpperTriangular matrix is not UpperTriangular
For sparse Gaussian processes, one often wants to parametrize the variational distribution using its Cholesky factors, which form an upper-triangular matrix and are trainable.

However, when taking gradients, Zygote instead computes the gradient with respect to all entries in the UpperTriangular matrix, including ones that are set to zero by virtue of it being UpperTriangular. This is related to #163.

For the moment, a workaround suitable for training models is to simply call `UpperTriangular(x)` on the upper-triangular matrix `x` before using it.

### LINKED ISSUE #917: Trying to differentiate a function with complex and real inputs results in error
I want to evaluate the hessian of a $\mathbb C^n \times \mathbb R^m \to \mathbb R$  function.
The actual function has several inputs, some of which are real and some of which are complex. To generate the hessian, I create a wrapper function with one real vector as argument and create the complex and real arguments for the actual function from this.

I get the following error, though:

```
julia> Zygote.hessian(fun, rand(9))
ERROR: MethodError: no method matching extract(::Array{Complex{ForwardDiff.Dual{Nothing,Float64,12}},1})
Closest candidates are:
  extract(::ForwardDiff.Dual) at /home/constantin/.julia/packages/Zygote/KpME9/src/lib/forward.jl:12
  extract(::AbstractArray{ForwardDiff.Dual{T,V,N},N1} where N1) where {T, V, N} at /home/constantin/.julia/packages/Zygote/KpME9/src/lib/forward.jl:14
Stacktrace:
 [1] forward_jacobian(::Zygote.var"#1086#1087"{typeof(Ropt3)}, ::Array{Float64,1}, ::Val{12}) at /home/constantin/.julia/packages/Zygote/KpME9/src/lib/forward.jl:23
 [2] forward_jacobian(::Function, ::Array{Float64,1}) at /home/constantin/.julia/packages/Zygote/KpME9/src/lib/forward.jl:40
 [3] hessian(::Function, ::Array{Float64,1}) at /home/constantin/.julia/packages/Zygote/KpME9/src/lib/utils.jl:113
 [4] top-level scope at REPL[15]:1
 [5] run_repl(::REPL.AbstractREPL, ::Any) at /tmp/portage/dev-lang/julia-1.5.3/work/julia-1.5.3/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
```

MWE
```julia
using Zygote

function fun(v)
    c = v[1:3] + v[4:6]*im
    r = v[7:9]
    sum(r .* abs2.(c)) # This would be calling my actual function depending on r and c
end

Zygote.hessian(fun, rand(9))
```

### PR DESCRIPTION
**Pull request by mcabbott**
This starts building ChainRulesCore's type projection story into how Zygote handles broadcasting, and into its user-facing functions. This will already be called in some rules handled by ChainRules, but this applies it a bit more broadly. 

After:
```julia
julia> gradient(x->imag(x + 2.0*im), 3.0)  # https://github.com/FluxML/Zygote.jl/issues/342
(0.0,)

julia> gradient(x -> getindex(x,2,1), Diagonal(rand(3,3)))[1]  # https://github.com/FluxML/Zygote.jl/issues/402
3×3 Diagonal{Float64, Vector{Float64}}:
 0.0   ⋅    ⋅ 
  ⋅   0.0   ⋅ 
  ⋅    ⋅   0.0

julia> gradient(x -> sum(sqrt.(x .+ 1)), [1,2,3]')[1]  # previously became a matrix
1×3 adjoint(::Vector{Float64}) with eltype Float64:
 0.353553  0.288675  0.25
```
Before:
```julia
julia> gradient(x->imag(x + 2.0*im), 3.0) 
(0.0 + 1.0im,)

julia> gradient(x -> getindex(x,2,1), Diagonal(rand(3,3)))[1]
3×3 Zygote.OneElement{Float64, 2, Tuple{Int64, Int64}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}:
 0.0  0.0  0.0
 1.0  0.0  0.0
 0.0  0.0  0.0

julia> gradient(x -> sum(sqrt.(x .+ 1)), [1,2,3]')[1]
1×3 Matrix{Float64}:
 0.353553  0.288675  0.25
```

Replaces #965, or most of it.

~~Many tests will fail, including most of the FFT tests I think, since those tend to return a complex gradient for a real input.~~ FFT tests are unchanged. 

Closes #342, closes #402. Fixes #917, fixes #431.

Closes https://github.com/FluxML/Flux.jl/issues/886

### CODE REVIEW

File: src/compiler/interface.jl [hunk 1]
```diff
@@ -123,26 +144,15 @@ julia> haskey(g, z)  # only x and y are parameters
...
-
-Container for implicit parameters, used when differentiating
-a zero-argument funtion `() -> loss(A, B)` with respect to `A, B`.
-"""
-struct Params
-  order::Buffer # {Any, Vector{Any}}
-  params::IdSet{Any} # TODO store ids only
+function gradient(f, ps::Params)
+  y, back = pullback(f, ps)
+  back(sensitivity(y))
```
Comment (mcabbott) [inline src/compiler/interface.jl:149]: `struct Params` hasn't changed. I just had to make a separate method `gradient(f, ps::Params)` and move that below it, the diff is confused. 

The reason that's separate is that projection doesn't happen for Params at all right now. But perhaps it should.

File: src/compiler/interface.jl [hunk 2]
```diff
@@ -73,7 +73,8 @@ julia> gradient([7, 11], 0, 1) do x, y, d
 """
 function gradient(f, args...)
   y, back = pullback(f, args...)
-  return back(sensitivity(y))
+  grad = back(sensitivity(y))
+  map(_project, args, grad)
```
Comment (mzgubic) [inline src/compiler/interface.jl:77]: do we want this at the `gradient` or the `pullback` level?

**Comment by mcabbott** [comment]
One side-effect of this is that it makes this wrong answer into an error:
```julia
julia> gradient((x,y) -> sum(map(+,x,y)), [1,2], [3,4,5,6])  # before
([1, 1], [1, 1])

julia> gradient((x,y) -> sum(map(+,x,y)), [1,2], [3,4,5,6])  # after
ERROR: DimensionMismatch("variable with size(x) == (4,) cannot have a gradient with size(dx) == (2,)")
Stacktrace:
 [1] (::ChainRulesCore.ProjectTo{AbstractArray, NamedTuple{(:element, :axes), Tuple{ChainRulesCore.ProjectTo{Float64, NamedTuple{(), Tuple{}}}, Tuple{Base.OneTo{Int64}}}}})(dx::Vector{Int64})
   @ ChainRulesCore ~/.julia/packages/ChainRulesCore/ySyqy/src/projection.jl:197
```

File: src/compiler/interface.jl (hunk 2 above)
Comment (mcabbott) [reply src/compiler/interface.jl:77]: My thinking was to start small! Applying it to `gradient` applies it to the user-facing calls, once. Applying it to `pullback` or `_pullback` inserts it into many more places internally... maybe it'll make `sin'''(1.0)` unhappy.

**Comment by DhairyaLGandhi** [comment]
That error seems awkward to me. Previously, the Julia behaviour of the function was the reason behind this operation. Presumably, the resultant gradient should be sized appropriately, not error.

File: src/compiler/interface.jl [hunk 3]
```diff
@@ -95,11 +97,32 @@ true
 """
 function withgradient(f, args...)
   y, back = pullback(f, args...)
-  (val = y, grad = back(sensitivity(y)))
+  grad = back(sensitivity(y))
+  isnothing(grad) && return (val=y, grad=nothing)
```
Comment (DhairyaLGandhi) [inline src/compiler/interface.jl:101]: Why is this check necessary?

File: src/compiler/chainrules.jl [hunk 4]
```diff
@@ -128,6 +128,39 @@ Convert `x` from the format Zygote uses internally to differentials types ChainR
   ChainRules.Tangent{Any, typeof(xp)}(xp)
 end
 
+"""
+  _project(x)(dx)
```
Comment (DhairyaLGandhi) [inline src/compiler/chainrules.jl:132]: This sound like it should be in CRC, not zygote.

cc @oxinabox

File: src/lib/broadcast.jl [hunk 5]
```diff
@@ -45,18 +45,20 @@ function Base.reducedim_init(::typeof(identity), ::typeof(accum), A::AbstractArr
   Base.reducedim_initarray(A, region, nothing, Union{Nothing,eltype(A)})
 end
 
-trim(x, Δ) = reshape(Δ, ntuple(i -> size(Δ, i), Val(ndims(x))))
```
Comment (DhairyaLGandhi) [inline src/lib/broadcast.jl:48]: I think doing this makes unbroadcast less generic, we don't need to define projections here afaict. Let's retain the current definition.

File: src/compiler/interface.jl (hunk 3 above)
Comment (mcabbott) [reply src/compiler/interface.jl:101]: It might not be. WIP, as it says.

File: src/compiler/chainrules.jl (hunk 4 above)
Comment (mcabbott) [reply src/compiler/chainrules.jl:132]: If you check the CRC issues, you will see much discussion of this exact point. WIP, as it says.

File: src/lib/broadcast.jl (hunk 5 above)
Comment (mcabbott) [reply src/lib/broadcast.jl:48]: What case exactly is not handled, if this is less generic?

Comment (DhairyaLGandhi) [reply src/lib/broadcast.jl:48]: It restricts it to what can be handled by `_project` as opposed to simple sizes and lengths of arrays.

File: src/lib/broadcast.jl [hunk 6]
```diff
@@ -45,18 +45,20 @@ function Base.reducedim_init(::typeof(identity), ::typeof(accum), A::AbstractArr
...
-  length(x) == length(x̄) ? trim(x, x̄) :
-    trim(x, accum_sum(x̄, dims = ntuple(i -> size(x, i) == 1 ? i : ndims(x̄)+1, Val(ndims(x̄)))))
-
+function unbroadcast(x::AbstractArray, x̄)
+  N = ndims(x̄)
+  if length(x) == length(x̄)
+    _project(x, x̄)  # ProjectTo handles reshape, offsets, structured matrices, row vectors
+  else
+    tup = filter(d -> size(x, d) == 1, ntuple(identity, N))
+    dims = length(tup) == 1 ? only(tup) : tup  # avoid sum(xbar, dims=(1,)) as e.g. sum(SA[1 2; 3 4], dims=(1,)) fails
```
Comment (DhairyaLGandhi) [inline src/lib/broadcast.jl:54]: Is there a downside to passing the tuple?

Comment (mcabbott) [reply src/lib/broadcast.jl:54]: Did you try the example provided on precisely the line you quoted?

Comment (DhairyaLGandhi) [reply src/lib/broadcast.jl:54]: Oh the comment goes beyond the dims. Still, that seems like a SA issue. Do they have a corresponding issue to support the syntax? Do you have a link?

Comment (DhairyaLGandhi) [reply src/lib/broadcast.jl:54]: Found https://github.com/JuliaArrays/StaticArrays.jl/pull/909

Comment (DhairyaLGandhi) [reply src/lib/broadcast.jl:54]: Yeah, so we can avoid this line in that case and SA can make a release that fixes the bug.

File: src/compiler/chainrules.jl [hunk 7]
```diff
@@ -123,11 +123,35 @@ Convert `x` from the format Zygote uses internally to differentials types ChainR
...
+  _project(x, dx)
+
+Uses `ChainRulesCore.ProjectTo` to standardise the gradient `dx` for type & shape.
+Also handles some Zygote-specific corrections, such as `x::Array, dx::Tuple`.
+Safe to apply to arbitrary input.
+"""
+@inline function _project(x::Union{Numeric, Ref{<:Numeric}}, dx)
+  wrap_chainrules_output(ProjectTo(x)(wrap_chainrules_input(dx)))
+end
+_project(x::AbstractArray, dx) = dx isa AbstractArray ? reshape(dx, axes(x)) : dx
```
Comment (DhairyaLGandhi) [inline src/compiler/chainrules.jl:142]: This can be broken down into a different method

File: src/compiler/interface.jl [hunk 8]
```diff
@@ -68,15 +68,20 @@ julia> gradient([7, 11], 0, 1) do x, y, d
...
-([14.0, 22.0], 2, nothing)
+([14.0, 22.0], 2.0, nothing)
 ```
 """
 function gradient(f, args...)
   y, back = pullback(f, args...)
-  return back(sensitivity(y))
+  grad = back(sensitivity(y))
+  isnothing(grad) ? nothing : map(_project, args, grad)
 end
```
Comment (DhairyaLGandhi) [inline src/compiler/interface.jl:78]: You can add a method to `_project` and avoid this change

**Review by DhairyaLGandhi — CHANGES_REQUESTED** [review]

**Comment by oxinabox** [comment]
Is there a reason not to pull all of broadcasting down into ChainRules.jl?
Probably combined with setting up Zygote to claim that ForwardDiff is it's ForwardMode AD?

**Comment by DhairyaLGandhi** [comment]
Why don't we give Zygote.Forward more love? It's better for neural networks.

**Comment by mcabbott** [comment]
> Is there a reason not to pull all of broadcasting down into ChainRules.jl?

One reason not to is that Zygote's un-fused broadcast might not be the last word here. Maybe you can write a fused forward broadcast in Diffractor which would be hopelessly slow here. I think there's a lot of exploring left to be done. Unlike the basic rules in ChainRules, where we can write a pretty close to optimal rule once & let everything use it.

Anyway this PR has much more modest goals. In the linked Flux issues it comes pretty close to entirely removing the penalty for mixing up your eltypes. And it fixes a lot of Zygote issues about real/complex.

**Comment by DhairyaLGandhi** [comment]
Mixing eltypes is going to get really important with low precision work picking up the pace. We shouldn't have to write custom passes for every operation related to 16 bit floats

**Comment by mcabbott** [comment]
Yes there have been rumours of mixed-precision training for ages. I don't see any obvious problem though. It does not involve randomly mixing types and hoping that Julia's promotion will figure it out.

Complex/real has been discussed at great length. This PR really isn't the place to argue it; if you think it's wrong you should open an issue on ChainRulesCore and make your case.

> Wouldn't we expect complex numbers to have gradients with complex types?

Err, they do? There would be a lot of broken tests if that were altered. I think you may have misunderstood what problem this projection solves. The first message has examples, and links to issues closed.

File: src/compiler/chainrules.jl (hunk 7 above)
Comment (mcabbott) [reply src/compiler/chainrules.jl:142]: Can you write exactly what method you prefer? There are obviously always other ways to write things.

File: src/compiler/interface.jl (hunk 8 above)
Comment (mcabbott) [reply src/compiler/interface.jl:78]: > You can add a method to _project and avoid this change

Can you write exactly what method that would be?

File: src/compiler/chainrules.jl [hunk 9]
```diff
@@ -123,11 +123,33 @@ Convert `x` from the format Zygote uses internally to differentials types ChainR
 """
 @inline wrap_chainrules_input(x) = x
 @inline wrap_chainrules_input(::Nothing) = ChainRules.ZeroTangent()
+@inline wrap_chainrules_input(::AbstractArray{Nothing}) = ChainRules.ZeroTangent()
```
Comment (oxinabox) [inline src/compiler/chainrules.jl:126]: This takes us another step closer to #1057 
(but avoids the worst cases of it) still

File: src/compiler/chainrules.jl [hunk 10]
```diff
@@ -123,11 +123,33 @@ Convert `x` from the format Zygote uses internally to differentials types ChainR
...
+
+# Restore splatted arrays
+_project(x::AbstractArray, dx::Tuple) = _project(x, reshape(collect(dx), axes(x)))
+
+# Piracy:
+# wrap_chainrules_input doesn't handle array of Union{Int,Nothing}
+(::ChainRulesCore.ProjectTo)(::Nothing) = ChainRulesCore.NoTangent()
+
+# CRC likes Tangent{<:Complex}, but Zygote makes Tangent{Any}
+(project::ProjectTo{<:Complex})(dx::Tangent) = project(Complex(dx.re, dx.im))
```
Comment (oxinabox) [inline src/compiler/chainrules.jl:151]: we could probably relax that one in CRC really.

File: src/compiler/chainrules.jl [hunk 11]
```diff
@@ -123,11 +123,33 @@ Convert `x` from the format Zygote uses internally to differentials types ChainR
...
+@inline function _project(x, dx)
+  wrap_chainrules_output(ProjectTo(x)(wrap_chainrules_input(dx)))
+end
+
+# Restore splatted arrays
+_project(x::AbstractArray, dx::Tuple) = _project(x, reshape(collect(dx), axes(x)))
+
+# Piracy:
+# wrap_chainrules_input doesn't handle array of Union{Int,Nothing}
+(::ChainRulesCore.ProjectTo)(::Nothing) = ChainRulesCore.NoTangent()
```
[the remark this answers is not in the document]
Comment (mcabbott) [reply src/compiler/chainrules.jl:148]: I think that didn't work. CRC was trying to do `map((f,x) -> f(x), project.elements, [1,2,nothing])` and this doesn't call `_project`.

File: src/compiler/chainrules.jl (hunk 9 above)
Comment (mcabbott) [reply src/compiler/chainrules.jl:126]: Ok. But this should have no bad side effects right? No extra memory, no conflict with doing #1057 later?

File: src/compiler/chainrules.jl (hunk 11 above)
[the remark this answers is not in the document]
Comment (mcabbott) [reply src/compiler/chainrules.jl:148]: This could be in CRC I guess, harmless to accept `nothing` since what else could it mean? But maybe you'd rather that be an error in general?

File: test/gradcheck.jl [hunk 12]
```diff
@@ -1403,6 +1403,17 @@ end
...
+
+  # Many of these tests check a complex gradient to a function with real input. This is now
+  # clamped to real by ProjectTo, but to run the old tests, use here the old gradient function:
+  function oldgradient(f, args...)
+    y, back = Zygote.pullback(f, args...)
+    back(Zygote.sensitivity(y))
+  end
+  # Eventually these rules and tests will be moved to ChainRules.jl, at which point the tests
+  # can be updated to use real / complex consistently.
+  # https://github.com/JuliaMath/AbstractFFTs.jl/pull/58
```
Comment (oxinabox) [inline test/gradcheck.jl:1415]: Normally I would not be OK with this defining `oldgradient` as it is a super-gross hack.
But if we can outright just delete all these tests entirely once that PR is merge than I am down with it.

File: src/compiler/chainrules.jl (hunk 9 above)
Comment (oxinabox) [reply src/compiler/chainrules.jl:126]: Correct.

File: test/gradcheck.jl (hunk 12 above)
Comment (mcabbott) [reply test/gradcheck.jl:1415]: Yea I lost quite a few hours trying to fix these. They are pretty convoluted tests.

File: src/compiler/chainrules.jl (hunk 11 above)
[the remark this answers is not in the document]
Comment (mcabbott) [reply src/compiler/chainrules.jl:148]: Yea so then better here as piracy. Tests of CR etc. will run without this, and catch stray `nothing`s. It's a bit ugly but not the worst thing in Zygote for sure.

File: src/compiler/chainrules.jl (hunk 10 above)
Comment (mcabbott) [reply src/compiler/chainrules.jl:151]: I can if you like. But do we want it allowed in general?

File: src/lib/broadcast.jl [hunk 13]
```diff
@@ -45,18 +45,20 @@ function Base.reducedim_init(::typeof(identity), ::typeof(accum), A::AbstractArr
...
-  size(x) == size(x̄) ? x̄ :
-  length(x) == length(x̄) ? trim(x, x̄) :
-    trim(x, accum_sum(x̄, dims = ntuple(i -> size(x, i) == 1 ? i : ndims(x̄)+1, Val(ndims(x̄)))))
-
+function unbroadcast(x::AbstractArray, x̄)
+  N = ndims(x̄)
+  if length(x) == length(x̄)
+    _project(x, x̄)  # ProjectTo handles reshape, offsets, structured matrices, row vectors
+  else
+    tup = filter(d -> size(x, d) == 1, ntuple(identity, N))
```
Comment (oxinabox) [inline src/lib/broadcast.jl:53]:
```suggestion
    tup = filter(d -> size(x, d) == 1, ntuple(identity, N))  # same as `Tuple(findall(==(1), size(x)))` but carefully optimized
```

Comment (mcabbott) [reply src/lib/broadcast.jl:53]: If it needs a comment, can it be even less optimised? 
```suggestion
    tup = filter(d -> size(x, d) == 1, ntuple(identity, N))  # like findall(size(x) .== 1) but optimised 
```

Comment (oxinabox) [reply src/lib/broadcast.jl:53]: If we didn't need a `Tuple` here then it is much faster if we can do `findall==(1), size(x))`

```julia
julia> const x = rand(3,1,1,2,1);
WARNING: redefinition of constant x. This may fail, cause incorrect answers, or produce other errors.

julia> @btime filter(d -> size(x, d) == 1, ntuple(identity, $(ndims(x))))
  118.460 ns (3 allocations: 80 bytes)
(2, 3, 5)

julia> @btime Tuple(findall(==(1), size($x)))
  154.346 ns (4 allocations: 240 bytes)
(2, 3, 5)

julia> @btime findall(==(1), size($x))
  54.909 ns (3 allocations: 208 bytes)
3-element Vector{Int64}:
 2
 3
 5
```

**Review by oxinabox — APPROVED** [review]
Other than a few last comments this seem good to me.

Might want to wait for @DhairyaLGandhi  to reply to the comments he made initially when this was openned, but it has been a while waiting.
I will ping him on slack.
Maybe give him a day or so, then if he is too busy we can merge and make follow ups later.

File: src/lib/broadcast.jl (hunk 13 above)
Comment (mcabbott) [reply src/lib/broadcast.jl:53]: The weird hack of `ndims() + 1` is still the fastest. We could revert to that. My hope was to let more things work with StaticArrays but maybe we settle for not making things worse. 
```
julia> @btime unbroadcast($(rand(1,3)), $(rand(3,3)));  # original
  154.998 ns (5 allocations: 224 bytes)

julia> @btime unbroadcast2($(rand(1,3)), $(rand(3,3)));  # as in PR
  889.191 ns (3 allocations: 112 bytes)

julia> @btime unbroadcast3($(rand(1,3)), $(rand(3,3)));  # with size(x) .== 1
  198.840 ns (8 allocations: 432 bytes)
```

File: src/lib/broadcast.jl [hunk 14]
```diff
@@ -45,18 +45,20 @@ function Base.reducedim_init(::typeof(identity), ::typeof(accum), A::AbstractArr
...
+    dims = length(tup) == 1 ? first(tup) : tup  # avoid sum(xbar, dims=(1,)) as e.g. sum(SA[1 2; 3 4], dims=(1,)) fails
```
Comment (mcabbott) [inline src/lib/broadcast.jl:54]:
```suggestion
    dims = ntuple(d -> size(x, d) == 1 ? d : ndims(x̄)+1, ndims(x̄))
```

File: src/lib/broadcast.jl (hunk 13 above)
Comment (oxinabox) [reply src/lib/broadcast.jl:53]: lets wrap whatever we come up with in a function like `singleton_dims(x)` or something, so we can encapsulate that complexity away form the implementation of `unbroadcast`

Comment (mcabbott) [reply src/lib/broadcast.jl]: For now I've put it back how it was; we can tackle some tidy up on another day.

File: src/compiler/interface.jl (hunk 8 above)
Comment (DhairyaLGandhi) [reply src/compiler/interface.jl:78]: Something like `_project(x, ::Nothing) = nothing` maybe

File: test/cuda.jl [hunk 15]
```diff
@@ -6,7 +6,11 @@ CUDA.allowscalar(false)
 # Test GPU movement inside the call to `gradient`
 @testset "GPU movement" begin
   r = rand(Float32, 3,3)
-  @test gradient(x -> sum(cu(x)), r)[1] isa Array{Float32, 2}
+  if VERSION < v"1.6"
+    @test gradient(x -> sum(cu(x)), r)[1] isa Matrix{Float32}
+  else
+    @test_broken gradient(x -> sum(cu(x)), r)[1] isa Matrix{Float32}
```
Comment (DhairyaLGandhi) [inline test/cuda.jl:12]: Is this still the case? Should be fixed on master

Comment (mcabbott) [reply test/cuda.jl]: Indeed, looks like it is fixed.

File: src/compiler/interface.jl (hunk 8 above)
Comment (mcabbott) [reply src/compiler/interface.jl:78]: This is easy to try:
```
julia> _project(x, ::Nothing) = nothing
_project (generic function with 1 method)

julia> map(_project, (1,2,3), nothing)
ERROR: MethodError: no method matching length(::Nothing)
```

**Comment by DhairyaLGandhi** [comment]
I did respond on the slack where I'd mentioned wanting to take a look at it today.
