### PR TITLE
[WIP] Fix issue #152, #154

### LINKED ISSUE #152: Broadcasting causes incorrect gradient for complex numbers
Sample code

```julia
using Zygote
julia> h1(a) = real((a*conj(a)));

julia> h2(a) = real((a.*conj(a)));

julia> h3(a) = real(([a].*conj([a])))[];

julia> h1'(0.3im)
0.0 + 0.6im

julia> h2'(0.3im)
ERROR: MethodError: no method matching mapfoldl_impl(::typeof(identity), ::typeof(Zygote.accum), ::NamedTuple{(:dims,),Tuple{Colon}}, ::Complex{Float64})
Closest candidates are:
  mapfoldl_impl(::Any, ::Any, ::NamedTuple{(:init,),T} where T<:Tuple, ::Any, ::Any...) at reduce.jl:40
  mapfoldl_impl(::Any, ::Any, ::NamedTuple{(),T} where T<:Tuple, ::Any) at reduce.jl:55
Stacktrace:
 [1] #mapfoldl#187(::Base.Iterators.Pairs{Symbol,Colon,Tuple{Symbol},NamedTuple{(:dims,),Tuple{Colon}}}, ::Function, ::Function, ::Function, ::Complex{Float64}) at ./reduce.jl:72
 [2] (::getfield(Base, Symbol("#kw##mapfoldl")))(::NamedTuple{(:dims,),Tuple{Colon}}, ::typeof(mapfoldl), ::Function, ::Function, ::Complex{Float64}) at ./none:0
 [3] #mapreduce#191(::Base.Iterators.Pairs{Symbol,Colon,Tuple{Symbol},NamedTuple{(:dims,),Tuple{Colon}}}, ::Function, ::Function, ::Function, ::Complex{Float64}) at ./reduce.jl:205
 [4] (::getfield(Base, Symbol("#kw##mapreduce")))(::NamedTuple{(:dims,),Tuple{Colon}}, ::typeof(mapreduce), ::Function, ::Function, ::Complex{Float64}) at ./none:0
 [5] #reduce#192(::Base.Iterators.Pairs{Symbol,Colon,Tuple{Symbol},NamedTuple{(:dims,),Tuple{Colon}}}, ::Function, ::Function, ::Complex{Float64}) at ./reduce.jl:361
 [6] (::getfield(Base, Symbol("#kw##reduce")))(::NamedTuple{(:dims,),Tuple{Colon}}, ::typeof(reduce), ::Function, ::Complex{Float64}) at ./none:0
 [7] #accum_sum#1040(::Function, ::Function, ::Complex{Float64}) at /home/leo/.julia/dev/Zygote/src/lib/broadcast.jl:33
 [8] accum_sum(::Complex{Float64}) at /home/leo/.julia/dev/Zygote/src/lib/broadcast.jl:33
 [9] unbroadcast(::Complex{Float64}, ::Complex{Float64}) at /home/leo/.julia/dev/Zygote/src/lib/broadcast.jl:47
 [10] (::getfield(Zygote, Symbol("##1054#1055")){Complex{Float64},Complex{Float64}})(::Float64) at /home/leo/.julia/dev/Zygote/src/lib/broadcast.jl:60
 [11] (::getfield(Zygote, Symbol("##2667#back#1056")){getfield(Zygote, Symbol("##1054#1055")){Complex{Float64},Complex{Float64}}})(::Float64) at /home/leo/.julia/dev/Zygote/src/lib/grad.jl:46
 [12] h2 at ./REPL[29]:1 [inlined]
 [13] (::typeof(∂(h2)))(::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface2.jl:0
 [14] (::getfield(Zygote, Symbol("##71#72")){typeof(∂(h2))})(::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:38
 [15] gradient(::Function, ::Complex{Float64}) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:47
 [16] (::getfield(Zygote, Symbol("##73#74")){typeof(h2)})(::Complex{Float64}) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:50
 [17] top-level scope at none:0

julia> h3'(0.3im)
0.0 - 0.6im
```

An array wrapper changes to behavior to the wrong direction. This is really wield... Which part of code should I look into?

### PR DESCRIPTION
**Pull request by GiggleLiu**
fix #152, #154

As well as the slow `conj` backward problem for array.

### CODE REVIEW

File: src/lib/forward.jl [hunk 1]
```diff
@@ -42,9 +42,9 @@ function forward_jacobian(f, x)
 end
 
 vec_scalar(x) = vec(x)
-vec_scalar(x::Real) = [x]
+vec_scalar(x::Number) = [x]
 reshape_scalar(x, y) = reshape(y, size(x))
-reshape_scalar(x::Real, y) = y[]
+reshape_scalar(x::Number, y) = y[]
```
Comment (MikeInnes) [inline src/lib/forward.jl]: Where is this needed/used? `forwarddiff` only works with real numbers.

File: src/lib/broadcast.jl [hunk 2]
```diff
@@ -59,6 +59,11 @@ unbroadcast(x::Union{Number,Ref}, x̄) = accum_sum(x̄)
 @adjoint broadcasted(::typeof(*), x, y) = x.*y,
   z̄ -> (nothing, unbroadcast(x, z̄ .* y), unbroadcast(y, z̄ .* x))
 
+@adjoint broadcasted(::typeof(*), x::Array{<:Number}, y::Array{<:Number}) = x.*y,
+  z̄ -> (nothing, unbroadcast(x, z̄ .* conj(y)), unbroadcast(y, z̄ .* conj(x)))
+@adjoint broadcasted(::typeof(*), x::Number, y::Number) = x.*y,
+  z̄ -> (nothing, unbroadcast(x, z̄ .* conj(y)), unbroadcast(y, z̄ .* conj(x)))
```
Comment (MikeInnes) [inline src/lib/broadcast.jl]: You may as well fold these definitions into the `Any` definition above and add the `conj` there. Also, best if it's broadcasted, so that it can be fused where possible.

File: src/lib/number.jl [hunk 3]
```diff
@@ -54,4 +54,9 @@ end
 @adjoint conj(x::Number) = conj(x), r̄ -> (conj(r̄),)
 @adjoint imag(x::Number) = imag(x), ī -> (real(ī)*im,)
 
+# Improve Array `conj`, `real` and `imag` Performance
+@adjoint real(x::AbstractArray) = real(x), r̄ -> (real(r̄),)
+@adjoint conj(x::AbstractArray) = conj(x), r̄ -> (conj(r̄),)
+@adjoint imag(x::AbstractArray) = imag(x), ī -> (real(ī)*im,)
```
Comment (MikeInnes) [inline src/lib/number.jl]: I would prefer this was fixed by adding the underlying rules for `broadcasted`, so that it also works when one does `conj.(x)` etc.

File: src/lib/forward.jl (hunk 1 above)
Comment (GiggleLiu) [reply src/lib/forward.jl]: It is not needed, I will roll back this change. Thanks for reading carefully.

File: src/lib/broadcast.jl (hunk 2 above)
Comment (GiggleLiu) [reply src/lib/broadcast.jl]: I thinkg for user defined `*` operations, using `conj` here may cause trouble? Calling the backward function of `*` with respect to specific types is desired.

File: src/lib/number.jl (hunk 3 above)
Comment (GiggleLiu) [reply src/lib/number.jl]: Do you mean adding backward for the following interface?
```julia
@adjoint broadcasted(::typeof(conj), x) 
```

Comment (GiggleLiu) [reply src/lib/number.jl]: Thanks, after adding this interface, `conj.` also works. The only problem is, here the rule is duplicated. Is it possible to reuse the backward rule defined for element-wise `conj`?

Comment (MikeInnes) [reply src/lib/number.jl]: Not yet unless we share things via DiffRules or add a macro for this. This is fine for now, thanks.

File: src/lib/broadcast.jl (hunk 2 above)
Comment (MikeInnes) [reply src/lib/broadcast.jl]: The only way to do that is to just delete the special case entirely and have it fall back.

It shouldn't matter though; if someone has defined a `*` operation it should behave mathematically like `*`, and if it doesn't have the same gradient I see that as their issue.

Comment (GiggleLiu) [reply src/lib/broadcast.jl]: > if someone has defined a * operation it should behave mathematically like *

This is often not true, maybe an error is better?

I tried to construct a counter example, but the error is not as expected
```julia
julia> using Zygote

julia> struct A
       data::Float64
       end
julia> Base.:*(a::A, b::A) = A(a.data+b.data)

julia> gradient(x->(A(x)*A(x)).data, 0.2)
(2.0,)

julia> gradient(x->([A(x)].*[A(x)])[].data, 0.2)
ERROR: MethodError: no method matching *(::NamedTuple{(:data,),Tuple{Float64}}, ::A)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:502
  *(::A, ::A) at REPL[6]:1
Stacktrace:
 [1] _broadcast_getindex_evalf at ./broadcast.jl:578 [inlined]
 [2] _broadcast_getindex at ./broadcast.jl:551 [inlined]
 [3] getindex at ./broadcast.jl:511 [inlined]
 [4] macro expansion at ./broadcast.jl:843 [inlined]
 [5] macro expansion at ./simdloop.jl:73 [inlined]
 [6] copyto! at ./broadcast.jl:842 [inlined]
 [7] copyto! at ./broadcast.jl:797 [inlined]
 [8] copy at ./broadcast.jl:773 [inlined]
 [9] materialize at ./broadcast.jl:753 [inlined]
 [10] (::getfield(Zygote, Symbol("##1054#1055")){Array{A,1},Array{A,1}})(::Array{Any,1}) at /home/leo/.julia/dev/Zygote/src/lib/broadcast.jl:60
 [11] #5 at /home/leo/.julia/dev/Zygote/src/lib/grad.jl:46 [inlined]
 [12] (::typeof(∂(getfield(Main, Symbol("##5#6"))())))(::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface2.jl:0
 [13] (::getfield(Zygote, Symbol("##71#72")){typeof(∂(getfield(Main, Symbol("##5#6"))()))})(::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:38
 [14] gradient(::Function, ::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:47
 [15] top-level scope at none:0
```

If I comment the following two lines in `broadcast.jl`
```julia
#@adjoint broadcasted(::typeof(*), x, y) = x.*y,
#  z̄ -> (nothing, unbroadcast(x, z̄ .* y), unbroadcast(y, z̄ .* x))
```
I got
```julia
julia> gradient(x->([A(x)].*[A(x)])[].data, 0.2)
ERROR: ArgumentError: tuple must be non-empty
Stacktrace:
 [1] first(::Tuple{}) at ./tuple.jl:77
 [2] unzip(::Tuple{}) at /home/leo/.julia/dev/Zygote/src/lib/array.jl:76
 [3] adjoint at /home/leo/.julia/dev/Zygote/src/lib/array.jl:83 [inlined]
 [4] _forward at /home/leo/.julia/dev/Zygote/src/lib/grad.jl:44 [inlined]
 [5] broadcasted at ./broadcast.jl:1166 [inlined]
 [6] #17 at ./none:1 [inlined]
 [7] _forward(::Zygote.Context, ::getfield(Main, Symbol("##17#18")), ::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface2.jl:0
 [8] _forward(::Function, ::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:31
 [9] forward(::Function, ::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:37
 [10] gradient(::Function, ::Float64) at /home/leo/.julia/dev/Zygote/src/compiler/interface.jl:46
 [11] top-level scope at none:0
```

I believe fixing this is beyond my ability.

Comment (MikeInnes) [reply src/lib/broadcast.jl]: I think it'd be reasonable to define `Numeric{T<:Number} = Union{T,AbstractArray{T}}` and restrict the broadcast definition to that, rather than the current `Any`, to avoid this kind of problem.

Comment (MikeInnes) [reply src/lib/broadcast.jl]: As another example could also define `map(A, B) = A*B` but at some point we just have to say ok, you're on your own here. We haven't nailed down exactly what that point is yet, but we can at least rule out certain cases that we're definitely not going to support.

File: src/lib/number.jl (hunk 3 above)
Comment (MikeInnes) [reply src/lib/number.jl]: So with the `broadcasted` definitions added, can we remove these without losing performance?

**Comment by MikeInnes** [comment]
Thanks @GiggleLiu!
