### PR TITLE
fix error while broadcasting

### LINKED ISSUE #724: Error with broadcasting ==
```julia
julia> using Zygote

julia> Zygote.gradient(x -> sum(x .* (x .== maximum(x))), rand(3))
([1.0, 0.0, 0.0],)

julia> Zygote.gradient(x -> sum(x .* (x .== maximum(x, dims=1))), rand(3,3))
ERROR: MethodError: no method matching size(::Nothing, ::Int64)
Closest candidates are:
  size(::BitArray{1}, ::Integer) at bitarray.jl:103
  size(::Tuple, ::Integer) at tuple.jl:22
  size(::Number, ::Integer) at number.jl:63
  ...
Stacktrace:
 [1] (::Zygote.var"#1086#1087"{Nothing})(::Int64) at /Users/me/.julia/packages/Zygote/pmW1K/src/lib/broadcast.jl:51
 [2] ntuple at ./ntuple.jl:42 [inlined]
 [3] trim(::Array{Float64,2}, ::Nothing) at /Users/me/.julia/packages/Zygote/pmW1K/src/lib/broadcast.jl:51
 [4] unbroadcast at /Users/me/.julia/packages/Zygote/pmW1K/src/lib/broadcast.jl:53 [inlined]
```
Julia 1.4 and Zygote v0.5.1.

### PR DESCRIPTION
**Pull request by gxyd**
Fixes #724

I'll go through the code-flow and see if the current solution is the best one.

**Test case**: I'll figure out how to write the test case for it on me own. I'll need sometime on that.

On this branch:
```jl
julia> Zygote.gradient(x -> sum(x .* (x .== maximum(x, dims=1))), rand(3,3))
([0.0 0.0 0.0; 1.0 1.0 1.0; 0.0 0.0 0.0],)

julia> Zygote.gradient(x -> sum(sum(x .== 0.5, dims=1)), rand(3,3))
(nothing,)

julia> Zygote.gradient(x -> sum(x .== 0.5), rand(3,3))
(nothing,)
```

### CODE REVIEW

**Comment by gxyd** [comment]
I couldn't find the documentation for as to how to run the test suite. Can someone please guide me through that?

**Comment by DhairyaLGandhi** [comment]
`Pkg.test("Zygote")` or `] test Zygote` from the repl with the Zygote environment activated

File: test/gradcheck.jl [hunk 1]
```diff
@@ -174,6 +174,11 @@ end
 @test gradient(det, 2.0)[1] == 1
 @test gradient(logdet, 2.0)[1] == 0.5
 
+
+@test gradient(x -> sum(x .== 0.5), rand(3, 3))[1] === nothing
+x1 = rand(3, 3)
```
Comment (gxyd) [inline test/gradcheck.jl:179]: I'm not sure if this is a good practise in Julia. Or should I create a `testset` put this under that?

**Comment by gxyd** [comment]
Also as I can see that the test of current master on Julia 1.0.

As the `README.md` states:
```
Zygote supports Julia 1.0 onwards, but we highly recommend using Julia 1.3 or later.
```
Is that error the reason for the recommendation of Julia 1.3 or later?

File: src/lib/broadcast.jl [hunk 2]
```diff
@@ -128,7 +128,7 @@ _broadcast(f::F, x...) where F = materialize(broadcasted(f, x...))
 
 _get(x::Tuple, i) = x[i]
 _get(::Nothing, i) = nothing
-collapse_nothings(xs::Vector{Nothing}) = nothing
+collapse_nothings(xs::Union{Vector{Nothing},Array{Nothing}}) = nothing
```
Comment (mcabbott) [inline src/lib/broadcast.jl:131]: Does this need the union, or could it just have `Array{Nothing}`?

File: test/gradcheck.jl (hunk 1 above)
Comment (mcabbott) [reply test/gradcheck.jl:179]: It's a bit of a free-for-all. Maybe there's an existing broadcasting testset these could join? 

It might be worth adding a comment linking to the issue, as some of the others have.

File: src/lib/broadcast.jl (hunk 2 above)
Comment (gxyd) [reply src/lib/broadcast.jl:131]: Oh, sorry. I don't recall the case for which I thought `Vector` isn't a Subtype of `Array`. I probably was wrong.

I agree, `AbstractArray{Nothing}` sound better.

**Comment by gxyd** [comment]
Hi @DhairyaLGandhi @mcabbott , can you please review the PR?

**Comment by CarloLucibello** [comment]
looks fine, thank you!

bors r+
